server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres-shipping:5432/shipping
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: eventia
    password: eventia_pass
    listener:
      simple:
        prefetch: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  rabbit:
    exchange: eventia.events
    queue: shipping.order.created
    routingKey:
      in: order.created
      out: shipping.dispatched
